site_name: Manuale di Scambiologia
docs_dir: manuale
theme:
  name: material
  language: it
  font: false
  logo: https://x.scambi.org/logo/scambi_yellow.svg
  favicon: https://x.scambi.org/favicon.ico
  repo_url: https://github.com/scambifestival/manuale
  features:
    - navigation.instant
extra_css:
  - scambi.css
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search:
      lang: 
        - en
        - it
  - social:
      cards_color:
        fill: "#69088D" 
        text: "#FFFFFF"
extra:
  alternate:
    - name: 🇬🇧
      link: /en/ 
      lang: en
    - name: 🇮🇹
      link: /
      lang: it