site_name: Manuale di Scambiologia
docs_dir: manuale
site_url: https://manuale.scambi.org
repo_url: https://github.com/scambifestival/manuale
repo_name: scambifestival/manuale
edit_uri: edit/main/manuale/
theme:
  name: material
  language: it
  font: false
  logo: scambi_yellow.svg
  favicon: https://x.scambi.org/favicon.ico
  features:
    - navigation.instant
extra_css:
  - scambi.css
extra:
  alternate:
    - name: 🇮🇹 Italiano
      link: /
      lang: it
    - name: 🇬🇧 English
      link: /en/ 
      lang: en
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - git-authors
  - search:
      lang: 
        - en
        - it
  - social:
      cards_layout_options:
        background_color: '#69088D' 
        color: "#FFFFFF"
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
